[package]
name = "cliphistory-frontend-rofi"
description = "cliphistory frontend using rofi's dmenu mode"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "cliphistory-frontend-rofi"
path = "src/main.rs"

[dependencies]
cliphistory-proto = { workspace = true }
cliphistory-frontend-common = { workspace = true }
anyhow = { workspace = true }
