[package]
name = "cliphistory-frontend-dmenu"
description = "cliphistory frontend using dmenu/bemenu"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "cliphistory-frontend-dmenu"
path = "src/main.rs"

[dependencies]
cliphistory-proto = { workspace = true }
cliphistory-frontend-common = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
